version: '3.8'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - product-service
      - order-service
      - shop
    networks:
      microservices-network:
        ipv4_address: 172.18.0.3

  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      microservices-network:
        ipv4_address: 172.18.0.7

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - microservices-network

  shop:
    build:
      context: ./applications/shop
    container_name: shop
    command: bash -c "bundle install && bundle exec rails db:create db:migrate && RAILS_ENV=development bundle exec rails s -b '0.0.0.0' -p 3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - product-service
      - order-service
    volumes:
      - ./applications/shop:/rails
      - ./config/local/shop.env:/rails/.env
    networks:
      microservices-network:
        ipv4_address: 172.18.0.4
    extra_hosts:
      - product.local:172.18.0.3
      - order.local:172.18.0.3

  product-service:
    build:
      context: ./services/product-service
    container_name: product-service
    command: bash -c "bundle install && bundle exec rails db:create db:migrate && RAILS_ENV=development bundle exec rails s -b '0.0.0.0' -p 3001"
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis
    volumes:
      - ./services/product-service:/rails
      - ./config/local/product-service.env:/rails/.env
    networks:
      microservices-network:
        ipv4_address: 172.18.0.5
    extra_hosts:
      - product.local:172.18.0.3
      - order.local:172.18.0.3

  order-service:
    build:
      context: ./services/order-service
    container_name: order-service
    command: bash -c "bundle install && bundle exec rails db:create db:migrate && RAILS_ENV=development bundle exec rails s -b '0.0.0.0' -p 3002"
    ports:
      - "3002:3002"
    depends_on:
      - db
      - redis
      - product-service
    volumes:
      - ./services/order-service:/rails
      - ./config/local/order-service.env:/rails/.env
    networks:
      microservices-network:
        ipv4_address: 172.18.0.6
    extra_hosts:
      - product.local:172.18.0.3
      - order.local:172.18.0.3

networks:
  microservices-network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"

volumes:
  postgres_data:
